[package]
name = "example-autojoin"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-autojoin"
test = false

[dependencies]
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
tracing-subscriber = "0.3.15"

[dependencies.matrix-sdk]
path = "../../crates/matrix-sdk"
version = "0.6.0"
