[package]
name = "matrix-sdk-redis"
version = "0.1.0"
edition = "2021"
authors = ["Andy Balaam <andy.balaam@matrix.org>"]
repository = "https://github.com/matrix-org/matrix-rust-sdk"
description = "Redis Storage backend for matrix-sdk"
license = "Apache-2.0"
rust-version = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["crypto-store"]

crypto-store = [
    "dep:matrix-sdk-crypto",
    "matrix-sdk-base/e2e-encryption",
]
real-redis-tests = []

[dependencies]
async-trait = "0.1.53"
dashmap = "5.2.0"
futures-core = "0.3.21"
futures-util = { version = "0.3.21", default-features = false }
matrix-sdk-common = { version = "0.6.0", path = "../matrix-sdk-common" }
matrix-sdk-crypto = { version = "0.6.0", path = "../matrix-sdk-crypto", optional = true }
matrix-sdk-store-encryption = { version = "0.2.0", path = "../matrix-sdk-store-encryption" }
redis = { version = "0.21", features = ["tokio-comp"] }
ruma = { workspace = true }
serde = "1.0.136"
serde_json = "1.0.79"

[dev-dependencies]
matrix-sdk-base = { path = "../matrix-sdk-base", features = ["testing"] }
matrix-sdk-crypto = { path = "../matrix-sdk-crypto", features = ["testing"] }
matrix-sdk-test = { path = "../../testing/matrix-sdk-test" }
once_cell = "1.10.0"
tokio = { version = "1.17.0", default-features = false, features = ["rt-multi-thread", "macros"] }
