[package]
name = "example-login"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-login"
test = false

[dependencies]
anyhow = "1"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
url = "2.2.2"

[dependencies.matrix-sdk]
path = "../../crates/matrix-sdk"
version = "0.6.0"
features = ["sso-login"]
