repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace

-   repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check

      # - id: clippy
      #   name: clippy
      #   language: system
      #   types: [file, rust]
      #   entry: cargo clippy --all-targets --all
      #   pass_filenames: false

      # - id: test
      #   name: test
      #   language: system
      #   files: '\.rs$'
      #   entry: cargo test --lib
      #   pass_filenames: false
