[package]
name = "matrix-sdk-rtc-livekit"
description = "LiveKit SDK wiring for matrix-sdk-rtc."
version = "0.16.0"
edition = "2024"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
license = "Apache-2.0"
rust-version.workspace = true
build = "build.rs"

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]

[features]
default = ["native-tls"]

native-tls = ["matrix-sdk-rtc/native-tls", "livekit/native-tls"]
rustls-tls = ["matrix-sdk-rtc/rustls-tls", "livekit/rustls-tls-native-roots"]
js = ["matrix-sdk-rtc/js"]
crypto = ["matrix-sdk-crypto", "matrix-sdk/e2e-encryption"]

[dependencies]
async-trait.workspace = true
livekit = { git = "https://github.com/onestacked/livekit-rust-sdks", branch = "EC-compat-changes" }
matrix-sdk.workspace = true
matrix-sdk-rtc.workspace = true
matrix-sdk-crypto = { workspace = true, optional = true }
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
