[package]
name = "example-persist-session"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-persist-session"
test = false

[dependencies]
anyhow = "1"
dirs = "5.0.1"
rand = "0.8.5"
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
# when copy-pasting this, please use a git dependency or make sure that you
# have copied the example as it was at the time of the release you use.
matrix-sdk = { path = "../../crates/matrix-sdk" }
