[package]
name = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "xtask"
test = false

[dependencies]
camino = "1.0.8"
clap = { version = "4.0.18", features = ["derive"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
fs_extra = "1"
uniffi_bindgen = { workspace = true }
xshell = "0.1.17"
