[package]
name = "matrix-sdk-ffi"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ffi"]
license = "Apache-2.0"
readme = "README.md"
rust-version = "1.56"
repository = "https://github.com/matrix-org/matrix-rust-sdk"

[lib]
crate-type = ["cdylib", "staticlib"]

[features]
default = ["with-runtime"]
with-runtime = ["tokio"]

[build-dependencies]
uniffi_build = { version = "0.17.0", features = ["builtin-bindgen"] }

[dependencies]
anyhow = "1.0.51"
extension-trait = "1.0.1"
futures-core = "0.3.17"
futures-util = { version = "0.3.17", default-features = false }
matrix-sdk = { path = "../matrix-sdk" }
once_cell = "1.10.0"
parking_lot = "0.12.0"
sanitize-filename-reader-friendly = "2.2.1"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
thiserror = "1.0.30"
tokio = { version = "1", optional = true, features = ["rt-multi-thread", "macros"] }
tokio-stream = "0.1.8"
tracing = "0.1.32"
uniffi = "0.17.0"
uniffi_macros = "0.17.0"
