[package]
name = "example-rtc-livekit-join"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[package.metadata.release]
release = false

[[bin]]
name = "example-rtc-livekit-join"
test = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
futures-util.workspace = true
matrix-sdk = { path = "../../crates/matrix-sdk" }
matrix-sdk-base = { path = "../../crates/matrix-sdk-base" }
matrix-sdk-crypto = { path = "../../crates/matrix-sdk-crypto" }
matrix-sdk-rtc = { path = "../../crates/matrix-sdk-rtc" }
matrix-sdk-rtc-livekit = { path = "../../crates/matrix-sdk-rtc-livekit" }
reqwest.workspace = true
ruma.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
v4l = { version = "0.14", optional = true }

[lints]
workspace = true

[features]
v4l2 = ["dep:v4l"]
e2ee-per-participant = ["matrix-sdk-rtc-livekit/crypto", "matrix-sdk/experimental-send-custom-to-device"]
