[package]
authors = ["Damir JeliÄ‡ <poljar@termina.org.uk>"]
description = "Collection of common types and imports used in the matrix-sdk"
edition = "2018"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk-common"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
version = "0.2.0"

[features]
unstable-synapse-quirks = ["ruma/unstable-synapse-quirks"]

[dependencies]
instant = { version = "0.1.9", features = ["wasm-bindgen", "now"] }
serde = "1.0.119"
async-trait = "0.1.42"

[dependencies.ruma]
version = "0.0.2"
features = ["client-api", "unstable-pre-spec"]

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
uuid = { version = "0.8.1", default-features = false, features = ["v4", "serde"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "1.0.1"
default-features = false
features = ["sync"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-locks = { version = "0.6.0", default-features = false }
uuid = { version = "0.8.1", default-features = false, features = ["v4", "wasm-bindgen"] }
