[package]
authors = ["Damir JeliÄ‡ <poljar@termina.org.uk"]
description = "Collection of common types used in the matrix-sdk"
edition = "2018"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
keywords = ["matrix", "chat", "messaging", "ruma", "nio"]
license = "Apache-2.0"
name = "matrix-sdk-common"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
version = "0.1.0"

[dependencies]
js_int = "0.1.5"
# ruma-api = "0.16.1"
# ruma-client-api = "0.9.0"
# ruma-events = "0.21.2"
# ruma-identifiers = "0.16.1"

ruma = { git = "https://github.com/DevinR528/ruma", features = ["client-api", "rand"], branch = "matrix-sdk2"}
# ruma = { path = "../../ruma/ruma", features = ["client-api", "rand"] }

instant = { version = "0.1.4", features = ["wasm-bindgen", "now"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
uuid = { version = "0.8.1", features = ["v4"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies.tokio]
version = "0.2.21"
default-features = false
features = ["sync", "time", "fs"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
futures-locks = { git = "https://github.com/asomers/futures-locks", default-features = false }
uuid = { version = "0.8.1", features = ["v4", "wasm-bindgen"] }
