[package]
authors = ["Shrey Patel <shreyrg14@gmail.com>"]
description = "The search component to build a Matrix client library."
edition = "2024"
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
license = "Apache-2.0"
name = "matrix-sdk-search"
readme = "README.md"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
rust-version.workspace = true
version = "0.16.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--generate-link-to-definition"]

[dependencies]
aes = { version = "0.8.4", default-features = false }
byteorder.workspace = true
ctr = { version = "0.9.2", default-features = false}
hmac = { workspace = true, features = ["reset"] }
hkdf.workspace = true
matrix-sdk-test = { workspace = true, optional = true }
pbkdf2.workspace = true
rand.workspace = true
sha2.workspace = true
tantivy = { version = "0.25.0", default-features = false, features = ["mmap", "stopwords", "lz4-compression", "columnar-zstd-compression"] }
tracing = { workspace = true, features = ["attributes"] }
thiserror.workspace = true
ruma = { workspace = true , features = [
    "client-api-c",
    "events",
    "rand",
    "unstable-msc1767"
] }
zeroize.workspace = true

[dev-dependencies]
matrix-sdk-test.workspace = true
tempfile.workspace = true

[lints]
workspace = true

