[package]
homepage = "https://github.com/matrix-org/matrix-rust-sdk"
description = "Test utilities used in the Matrix Rust SDK"
keywords = ["matrix", "chat", "messaging", "ruma"]
license = "Apache-2.0"
name = "matrix-sdk-test-utils"
version = "0.16.0"
edition = "2024"
rust-version.workspace = true

[package.metadata.release]
release = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
ctor = "0.2.9"
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[lints]
workspace = true
