[package]
name = "matrix-sdk-sled"
version = "0.1.0"
edition = "2021"

[features]
default = ["state-store", "crypto-store"]

state-store = ["matrix-sdk-base"]
crypto-store = ["matrix-sdk-crypto"]

[dependencies]
anyhow = "1.0.57"
async-stream = "0.3.3"
async-trait = "0.1.53"
dashmap = "5.2.0"
futures-core = "0.3.21"
futures-util = { version = "0.3.21", default-features = false }
matrix-sdk-base = { path = "../matrix-sdk-base", optional = true }
matrix-sdk-common = { path = "../matrix-sdk-common" }
matrix-sdk-crypto = { path = "../matrix-sdk-crypto", optional = true }
matrix-sdk-store-encryption = { path = "../matrix-sdk-store-encryption" }
ruma = "0.6.1"
serde = "1.0.136"
serde_json = "1.0.79"
sled = "0.34.7"
thiserror = "1.0.30"
tokio = { version = "1.17.0", default-features = false, features = ["sync", "fs"] }
tracing = "0.1.34"

[dev-dependencies]
matrix-sdk-base = { path = "../matrix-sdk-base", features = ["testing"] }
matrix-sdk-crypto = { path = "../matrix-sdk-crypto", features = ["testing"] }
matrix-sdk-test = { version = "0.4.0", path = "../matrix-sdk-test" }
once_cell = "1.10.0"
tempfile = "3.3.0"
tokio = { version = "1.17.0", default-features = false, features = ["rt-multi-thread", "macros"] }
