[package]
name = "matrix-sdk-ui"
version = "0.6.0"
edition = "2021"

[features]
default = ["e2e-encryption", "native-tls", "experimental-room-list", "experimental-notification"]

e2e-encryption = ["matrix-sdk/e2e-encryption"]

native-tls = ["matrix-sdk/native-tls"]
rustls-tls = ["matrix-sdk/rustls-tls"]

experimental-room-list = ["experimental-sliding-sync", "dep:async-stream", "dep:eyeball-im-util"]
experimental-notification = ["experimental-sliding-sync", "dep:async-stream"]
experimental-sliding-sync = ["matrix-sdk/experimental-sliding-sync"]

testing = ["dep:eyeball-im-util"]

[dependencies]
async-once-cell = "0.5.2"
async-std = { version = "1.12.0", features = ["unstable"] }
async-stream = { workspace = true, optional = true }
async-trait = { workspace = true }
chrono = "0.4.23"
eyeball = { workspace = true }
eyeball-im = { workspace = true }
eyeball-im-util = { workspace = true, optional = true }
futures-core = { workspace = true }
futures-util = { workspace = true }
imbl = { version = "2.0.0", features = ["serde"] }
indexmap = "1.9.1"
matrix-sdk = { version = "0.6.2", path = "../matrix-sdk", default-features = false }
matrix-sdk-base = { version = "0.6.1", path = "../matrix-sdk-base" }
mime = "0.3.16"
once_cell = { workspace = true }
pin-project-lite = "0.2.9"
ruma = { workspace = true, features = ["unstable-sanitize"] }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true, features = ["attributes"] }

[dev-dependencies]
anyhow = { workspace = true }
assert-json-diff = "2.0"
assert_matches = { workspace = true }
ctor = { workspace = true }
eyeball-im-util = { workspace = true }
matrix-sdk = { version = "0.6.2", path = "../matrix-sdk", default-features = false, features = ["testing"] }
matrix-sdk-test = { version = "0.6.0", path = "../../testing/matrix-sdk-test" }
stream_assert = "0.1.0"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
wiremock = "0.5.13"

[[test]]
name = "integration"
required-features = ["testing"]
