[package]
name = "example-timeline"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-timeline"
test = false

[dependencies]
anyhow = "1"
futures = "0.3"
futures-signals = { version = "0.3.30", default-features = false }
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
url = "2.2.2"

[dependencies.matrix-sdk]
path = "../../crates/matrix-sdk"
features = ["experimental-timeline", "sled"]
version = "0.6.0"
