[package]
name = "example-timeline"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-timeline"
test = false

[dependencies]
anyhow = "1"
clap = "4.0.16"
futures = "0.3"
tokio = { version = "1.24.2", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
url = "2.2.2"

[dependencies.matrix-sdk]
path = "../../crates/matrix-sdk"
version = "0.6.0"

[dependencies.matrix-sdk-ui]
path = "../../crates/matrix-sdk-ui"
version = "0.6.0"
