[package]
name = "example-emoji-verification"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-emoji-verification"
test = false

[dependencies]
anyhow = "1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
clap = { version = "4.0.15", features = ["derive"] }
futures-util = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
# when copy-pasting this, please use a git dependency or make sure that you
# have copied the example as it was at the time of the release you use.
matrix-sdk = { path = "../../crates/matrix-sdk" }

[lints]
workspace = true
