[package]
name = "multiverse"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[package.metadata.release]
release = false

[[bin]]
name = "multiverse"
test = false

[dependencies]
clap = { workspace = true, features = ["derive", "env"] }
color-eyre = "0.6.5"
crossterm = "0.28.1"
futures-util.workspace = true
imbl.workspace = true
indexmap.workspace = true
itertools.workspace = true
matrix-sdk = { path = "../../crates/matrix-sdk", features = ["sso-login", "experimental-search"] }
matrix-sdk-base = { path = "../../crates/matrix-sdk-base" }
matrix-sdk-common = { path = "../../crates/matrix-sdk-common" }
matrix-sdk-ui = { path = "../../crates/matrix-sdk-ui" }
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
rpassword = "7.4.0"
serde_json.workspace = true
strum = { version = "0.27.2", features = ["derive"] }
textwrap = "0.16.2"
throbber-widgets-tui = "0.9.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber = { workspace = true, features = ["env-filter"] }
tui-framework-experiment = "0.4.0"
tui-textarea = "0.7.0"
tui-widget-list = "0.13.2"

[lints]
workspace = true
