[package]
name = "sled-state-inspector"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
atty = "0.2.14"
clap = "~3.1.12"
futures = { version = "0.3.21", default-features = false, features = ["executor"] }
matrix-sdk-base = { path = "../../crates/matrix-sdk-base", version = "0.5.0" }
matrix-sdk-sled = { path = "../../crates/matrix-sdk-sled", version = "0.1.0" }
ruma = "0.6.1"
rustyline = "9.1.2"
rustyline-derive = "0.6.0"
serde = "1.0.136"
serde_json = "1.0.79"
syntect = "4.6.0"
