[package]
name = "sled-state-inspector"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "sled-state-inspector"
test = false

[dependencies]
atty = "0.2.14"
clap = "3.2.4"
futures = { version = "0.3.21", default-features = false, features = ["executor"] }
matrix-sdk-base = { path = "../../crates/matrix-sdk-base", version = "0.5.0" }
matrix-sdk-sled = { path = "../../crates/matrix-sdk-sled", version = "0.1.0" }
ruma = { git = "https://github.com/ruma/ruma", rev = "ca8c66c885241a7ba3805399604eda4a38979f6b" }
rustyline = "10.0.0"
rustyline-derive = "0.7.0"
serde = "1.0.136"
serde_json = "1.0.79"
syntect = "5.0.0"
