[package]
name = "example-qr-login"
version = "0.1.0"
edition = "2024"
publish = false
license = "Apache-2.0"

[package.metadata.release]
release = false

[[bin]]
name = "example-qr-login"
test = false

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
futures-util.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tracing-subscriber.workspace = true
url.workspace = true

[dependencies.matrix-sdk]
# when copy-pasting this, please use a git dependency or make sure that you
# have copied the example as it was at the time of the release you use.
path = "../../crates/matrix-sdk"
