[package]
name = "example-qr-login"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-qr-login"
test = false

[dependencies]
anyhow = "1"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
clap = { version = "4.0.15", features = ["derive"] }
qrcode = { git = "https://github.com/kennytm/qrcode-rust/" }
futures-util = { workspace = true }
tracing-subscriber = { workspace = true }
url = "2.3.1"

[dependencies.matrix-sdk]
# when copy-pasting this, please use a git dependency or make sure that you
# have copied the example as it was at the time of the release you use.
path = "../../crates/matrix-sdk"
features = ["experimental-oidc"]
