[bindings.kotlin]
package_name = "org.matrix.rustcomponents.sdk"
cdylib_name = "matrix_sdk_ffi"
android_cleaner = true
# Checksums are incorrectly failing for users with 32bit (and sometimes 64bit?) devices at the moment
# Remove once https://github.com/mozilla/uniffi-rs/issues/2740 is fixed or JNI is used instead of JNA
omit_checksums = true
