[package]
name = "example-appservice-autojoin"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-appservice-autojoin"
test = false

[dependencies]
anyhow = "1"
tokio = { version = "1.20.1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = "0.3.15"
tracing = { workspace = true }

[dependencies.matrix-sdk-appservice]
path = "../../crates/matrix-sdk-appservice"
