[package]
name = "matrix-sdk-rtc"
description = "RTC helpers on top of matrix-rust-sdk (experimental)."
version = "0.16.0"
edition = "2024"
repository = "https://github.com/matrix-org/matrix-rust-sdk"
license = "Apache-2.0"
rust-version.workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]

[features]
default = ["native-tls"]

native-tls = ["matrix-sdk/native-tls"]
rustls-tls = ["matrix-sdk/rustls-tls"]
js = ["matrix-sdk/js"]

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
matrix-sdk.workspace = true
ruma.workspace = true
thiserror.workspace = true
tracing = { workspace = true, features = ["attributes"] }

[lints]
workspace = true
