[package]
name = "example-oidc-cli"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "example-oidc-cli"
test = false

[dependencies]
anyhow = { workspace = true }
axum = "0.7.4"
dirs = "5.0.1"
futures-util = { workspace = true, default-features = false }
matrix-sdk-ui = { path = "../../crates/matrix-sdk-ui" }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["util"] }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[dependencies.matrix-sdk]
path = "../../crates/matrix-sdk"
features = ["experimental-oidc"]

[lints]
workspace = true
