
version: '3'

services:

  synapse:
    build: .
    restart: "no"
    healthcheck:
      disable: true
    volumes:
      - matrix-rust-sdk-sliding-sync-ci-data:/data
      
    ports:
      - 8228:8008/tcp

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: syncv3
    healthcheck:
      test: ["pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  sliding-sync-proxy:
    image: ghcr.io/matrix-org/sliding-sync:v0.98.0
    links:
      - synapse
      - postgres
    environment:
      SYNCV3_SERVER: http://synapse:8008
      SYNCV3_SECRET: SUPER_SECRET
      SYNCV3_BINDADDR: ":8338" 
      SYNCV3_DB: "user=postgres password=postgres dbname=syncv3 sslmode=disable host=postgres"
    ports:
      - 8338:8338

volumes:
  matrix-rust-sdk-sliding-sync-ci-data:
