name: Documentation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  docs:
    name: All crates
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || !github.event.pull_request.draft

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Load cache
        uses: Swatinem/rust-cache@v1

      # Keep in sync with xtask docs
      - name: Build rust documentation
        uses: actions-rs/cargo@v1
        env:
          # Work around https://github.com/rust-lang/cargo/issues/10744
          CARGO_TARGET_APPLIES_TO_HOST: "true"
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options --cfg docsrs -Dwarnings"
        with:
          command: doc
          args: --no-deps --workspace --features docsrs

      - name: Build `matrix-sdk-crypto-nodejs` doc
        run: |
          cd bindings/matrix-sdk-crypto-nodejs
          npm install
          npm run build && npm run doc

      - name: Build `matrix-sdk-crypto-js` doc
        run: |
          cd bindings/matrix-sdk-crypto-js
          npm install
          npm run build && npm run doc

      - name: Prepare the doc hierarchy
        shell: bash
        run: |
          mkdir -p doc
          mkdir -p doc/bindings/matrix-sdk-crypto-nodejs/
          mkdir -p doc/bindings/matrix-sdk-crypto-js/
          mv target/doc/* doc/
          mv bindings/matrix-sdk-crypto-nodejs/docs/* doc/bindings/matrix-sdk-crypto-nodejs/
          mv bindings/matrix-sdk-crypto-js/docs/* doc/bindings/matrix-sdk-crypto-js/

      - name: Deploy documentation
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/
          force_orphan: true
